# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_gb',
            name='price_disc',
            field=models.FloatField(default=0, verbose_name='\u0426\u0435\u043d\u0430 \u0441\u043e \u0441\u043a\u0438\u0434\u043a\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='price_gb',
            name='price',
            field=models.FloatField(default=0, verbose_name='\u0426\u0435\u043d\u0430 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
