# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_auto_20160214_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_gb',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 2, 14, 9, 42, 39, 797490)),
        ),
    ]
