# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_auto_20160214_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_gb',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
