# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0010_auto_20160214_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_gb',
            name='date',
            field=models.DateField(default=datetime.date(2016, 2, 14)),
        ),
    ]
